### PR TITLE
Avoid specific dependency versions

### PR DESCRIPTION
**Pull request by hydroper**
Use `x.y` rather than `x.y.z` for Cargo dependencies.

### CODE REVIEW

**Comment by brendanzab** [comment]
Oooh nice! What will this buy us?

**Comment by hydroper** [comment]
@brendanzab Better build times for little gl tests (`cargo new, init` and etc.), 95% sure.

**Comment by hydroper** [comment]
You could do this change yourself and I'd be satisfied.

**Comment by hydroper** [comment]
@brendanzab It'll probably improve builds. You should know `z` is only a bugfix matter.

**Comment by brendanzab** [comment]
For pre-1.0 versions I normally include the revision number, and Cargo defaults to using the latest revision, but not the latest minimum version (which is usually a breaking change in pre-1.0 libs). I'm ok with removing the revision number for the post-1.0 libraries though.

**Comment by hydroper** [comment]
Ah, so the revision number won't cause issues in compilation, usually. I guess I got confused. This is a small commit, was just thinking it'd solve some worries with me.

**Pull request closed without merging**
