### PR TITLE
Bump webgl_generator and webgl_stdweb versions

### LINKED ISSUE #467: webgl_generator's crates.io uses an outdated version of the code
The version of webgl_generator on crates.io (https://crates.io/crates/webgl_generator) uses an outdated version of the code. The crate was last updated 5 months ago, but the code in the repository was updated 4 months ago. Can we push the latest version of webgl_generator to crates.io?

### PR DESCRIPTION
**Pull request by brendanzab**
Closes  #467

### CODE REVIEW

**Comment by brendanzab** [comment]
Ugh, the build keeps timing out on nightly

**Comment by benkonz** [comment]
should we add a `travis_wait` to the `cargo test` command?

**Comment by brendanzab** [comment]
Oh, do you think that would fix it?

**Comment by brendanzab** [comment]
Hum, interesting - just reading the docs! https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

**Comment by brendanzab** [comment]
Done! At last! Sorry for my slowness! 🤦‍♂️

**Pull request merged**
