### PR TITLE
Add WebGL IDL files as constants

### PR DESCRIPTION
**Pull request by Diggsey**

### CODE REVIEW

**Comment by brendanzab** [comment]
You'll also want to include these in the `Cargo.toml`'s `include` list: https://github.com/brendanzab/gl-rs/blob/2d23c1f9b79685224a2778a6a43ef2b9d50f827f/khronos_api/Cargo.toml#L17-L23

**Comment by Diggsey** [comment]
Thanks, fixed.

**Comment by Diggsey** [comment]
@brendanzab I'm implementing a webgl binding generator - there will be one initial implementation using `stdweb`. Please let me know how you see that fitting in: I'm currently doing it as a `webgl` submodule in the `gl_generator` crate which sits behind a feature flag.

**Comment by brendanzab** [comment]
Oh nice, this is super exciting! Feel free to make any improvements you see fit in gl_generator to make your life easier - always good to have new eyes viewing old code.

**Comment by brendanzab** [comment]
Might be easier to evaluate how it fits in once you have a WIP PR up. Not sure if it needs to be behind a feature flag, but it might be clearer why you decided to go down that route once you can show what you've done.

**Comment by Diggsey** [comment]
I should clarify a couple of things: there are two ways to use "webgl":
1) Via the emscripten compatibility layer: the program binds to a "normal" GLES API, and then emscripten automatically translates calls to webgl calls.
2) Directly, via the javascript API: the program needs some way to bind to javascript, and then it can directly call methods on a WebGLRenderingContext.

What I am implementing is 2, the direct interface.

It will need to be a different sort of generator, because the webgl-based APIs aren't be compatible with the "normal" GL ones, so it won't really share any code with the existing generators. I did plan to use a similar style though, in that there will be a shared IDL parsing layer, and then multiple generator implementations depending on how the "binding to javascript" part is done: the initial backend will use `stdweb` to bind to javascript.

I was going to put it behind a feature flag just to save bloating existing builds relying on gl_generator.

**Comment by SirVer** [comment]
@Diggsey just as a drive buy comment: I would be very excited to use this. I use `gl_generator` happily in https://github.com/googlecartographer/point_cloud_viewer and want to explore compiling it to webasm directly - your work would make my life much easier.

**Comment by brendanzab** [comment]
@SirVer: Awesome! You can check out the current progress on PR #433

**Pull request merged**
