### PR TITLE
Add support for ANGLE extensions to the generator.

### PR DESCRIPTION
**Pull request by emilio**
Not quite sure this is the right approach, but it does work. Happy to clean up
the bool argument or what not if you want.

Also, probably should make it a different crate if ANGLE stuff is not wanted in `khronos_api`, I don't know. 

Anyhow, does this look reasonable? If not, which approach should I take to fix this?

### CODE REVIEW

**Comment by emilio** [comment]
Review ping?

**Comment by emilio** [comment]
The context for this is https://bugzilla.mozilla.org/show_bug.cgi?id=1520953. We need to use some ANGLE extension to avoid stupid shader recompiles under our nose.

**Comment by emilio** [comment]
Nag? I'd really want to finish this work sometime this week. Thanks in advance :)

**Comment by brendanzab** [comment]
Thanks for the re-nag!

**Pull request merged**
