### PR TITLE
Update khronos api submodules to latest commit

### PR DESCRIPTION
**Pull request by MatusT**
Hello,

This pull request is only update of khronos apis using "git submodule update --remote --merge". These brings new extensions such as SPIR-V support(#425). 

Could you publish new version with these apis updated?

### CODE REVIEW

**Comment by tomaka** [comment]
It looks like the ARB_spirv extension was already in the repository, but not published on crates.io.
I'll publish a new version after this PR is merged.

**Comment by MatusT** [comment]
You are awesome. But now It seems that build fails. Looks like a new type was added: EGLint and needs conversion. I will try to add it :).

**Comment by MatusT** [comment]
So 2 things were added in order for this to compile with new apis:
1. " const EGLint *" => "*const types::EGLint" with comment that is it hacky workaround. I am completely new into this crate, so if you could give any hints how I could fix it properly, I will be glad to do it.
2. "EGLnsecsANDROID *" => "*mut type::EGLnsecsANDROID". EGLnsecsANDROID was there but without pointer type

**Comment by tomaka** [comment]
The whole `to_rust_ty` is more or less a hack because of Khronos' bad XML format.
However when it comes to the `EGLint`, maybe instead you could replace `match ty.as_ref()` with `match ty.as_ref().trim()` at the top of the function, so that white spaces are removed.

**Comment by MatusT** [comment]
Trim seems like a good workaround for now. I will also try to place merge request on EGL registry. There are exactly 2 instance of <param> const <ptype>EGLint</ptype> (with space) against 24 without space. One could say it is small mistake on their side.

**Comment by MatusT** [comment]
The fix with trim works but I had to remove few spaces on the left side of match as well.

**Pull request merged**
