### PR TITLE
Update xml-rs to 0.7.0 and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by brendanzab** [comment]
Sorry for the late merge - thanks!

**Comment by Eijebong** [comment]
Can this be released ?

**Comment by brendanzab** [comment]
Sorry, I need to figure out the troubles we are having on #427 first. I'll see if I can look at it tonight!

**Comment by Eijebong** [comment]
Sure, good luck with that :)

**Comment by brendanzab** [comment]
Published!

**Pull request merged**
