### PR TITLE
change lifetime to static

### PR DESCRIPTION
**Pull request by Cyres**
Since all function names are compiled into binary, it would be great to change the signature:
```diff
+ FnMut(&str) -> *const c_void` to `FnMut(&'static str) -> *const c_void
- FnMut(&str) -> *const c_void` to `FnMut(&str) -> *const c_void
```
My current dirty workaround is [transmuting](https://doc.rust-lang.org/std/mem/fn.transmute.html) it into a `'static` string

### CODE REVIEW

**Comment by tomaka** [comment]
I'm not sure I understand the PR. To me the changes are strictly inferior to what exist.

**Comment by Cyres** [comment]
With this PR you can use the provided proc addresses after loading without the need to copy them. I can change other generators as well.

It won't break any existing code, since the lifetime is relaxed (`'static` is the most relaxed lifetime) and it's working, since all touched `str`s are compiled into the binary.

**Comment by tomaka** [comment]
Ah yes, sorry. I looked at the PR too quickly. 👍 for me.

**Comment by brendanzab** [comment]
I just noticed you accidentally committed a `*.kate-swp` file. I'd probably recommend adding that pattern you your global `.gitignore` in your home directory to prevent this happening again.

**Comment by Cyres** [comment]
Oh, thanks, I didn't reviewed my commit. It's intended that the `*.kate-swp`-Files are not listed in my global .gitignore since it's notifies me, that these files were not saved before. Indeed, `static_struct_gen.rs` were not saved/commited.

**Pull request merged**
