### PR TITLE
Publish khronos_api 1.0.2

### PR DESCRIPTION
**Pull request by tomaka**

### CODE REVIEW

**Comment by tomaka** [comment]
Ok. Problem here. The khronos people decided to include the PDF files of every single version of their specs.
Therefore khronos_api is over the maximum allowed size of crates.io.

**Comment by tomaka** [comment]
Let's switch to git subtrees?

**Comment by tomaka** [comment]
Or read-tree. I'm not a git expert.

**Comment by Ralith** [comment]
Would [`package.exclude`](http://doc.crates.io/manifest.html#the-exclude-and-include-fields-optional) help? I use that in openvr-sys to keep the binaries at bay.

**Comment by brendanzab** [comment]
Oh dear, that's fun!

**Comment by brendanzab** [comment]
Wondering if we should opt-in with `package.include` or opt-out with `package.exclude` 🤔

**Pull request closed without merging**
